/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/brake.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/first-auto/brake.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['13482_Brake_Rotor_v1_L2'].geometry} material={materials.brake_rotor_body} rotation={[Math.PI, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/first-auto/brake.glb')
