/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/Home3d.glb --transform 
Files: public/model/Home3d.glb [211.7MB] > /home/mohamed/Desktop/Mohamed/work1/store/client/Home3d-transformed.glb [1.73MB] (99%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mosasha/Home3d-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Grid.geometry} material={materials['Material.013']} position={[10.434, 8.699, -5.392]} scale={33.608} />
      <group position={[17.005, 17.472, -5.408]} scale={[13.767, 8.475, 22.195]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.008']} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[1.333, 14.644, -10.288]} rotation={[0, 0, -Math.PI / 2]} scale={0.488} />
      <group position={[-16.56, 9.837, -24.672]} rotation={[0, Math.PI / 2, 0]} scale={2.906}>
        <mesh geometry={nodes.Cube032.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials.PaletteMaterial003} />
      </group>
      <mesh geometry={nodes.M_WheelFRBrakePad.geometry} material={materials.PaletteMaterial005} position={[-13.086, 10.281, -29.509]} rotation={[Math.PI / 2, 0, -1.571]} scale={0.565} />
      <mesh geometry={nodes.M_WheelFLTire.geometry} material={materials.PaletteMaterial006} position={[-19.786, 10.281, -29.509]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-1.336, -0.415, -1.336]} />
      <mesh geometry={nodes.M_GrillFan1.geometry} material={materials.PaletteMaterial007} position={[-15.307, 11.534, -32.472]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.13, 0.018, 0.13]} />
      <mesh geometry={nodes.M_BackLights.geometry} material={materials.PaletteMaterial008} position={[-16.56, 11.735, -13.699]} rotation={[0, Math.PI / 2, 0]} scale={2.906} />
      <mesh geometry={nodes.M_FrontLightBulbs4.geometry} material={materials.PaletteMaterial009} position={[-16.56, 9.53, -31.92]} rotation={[0, Math.PI / 2, 0]} scale={2.906} />
      <mesh geometry={nodes.gothic_coffee_table.geometry} material={materials.gothic_coffee_table} position={[18.368, 8.405, 8.08]} scale={6.534} />
    </group>
  )
}

useGLTF.preload('/Home3d-transformed.glb')
