/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Laptop bag.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    backpack_Cube_1: THREE.Mesh
    backpack_Cube_2: THREE.Mesh
    backpack_Cube_3: THREE.Mesh
    backpack_Cube_High: THREE.Mesh
  }
  materials: {
    None: THREE.MeshStandardMaterial
    ['None.001']: THREE.MeshStandardMaterial
    None_NONE: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/mosasha/model/Laptop_bag.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.backpack_Cube_1.geometry} material={materials.None} />
        <mesh geometry={nodes.backpack_Cube_2.geometry} material={materials['None.001']} />
        <mesh geometry={nodes.backpack_Cube_3.geometry} material={materials.None_NONE} />
      </group>
      <mesh geometry={nodes.backpack_Cube_High.geometry} material={materials.None} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}
// Must match the exact path string used inside useGLTF() above
useGLTF.preload('/mosasha/model/Laptop_bag.glb')