/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/vichle.glb --transform --types 
Files: public/model/vichle.glb [112.1MB] > /home/mohamed/Desktop/Mohamed/work1/store/client/vichle-transformed.glb [9.32MB] (92%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    glass: THREE.Mesh
    Body: THREE.Mesh
    tire_rubber: THREE.Mesh
    silicon: THREE.Mesh
    Frame: THREE.Mesh
    Secondary_Details004: THREE.Mesh
    FLR004: THREE.Mesh
    Console004: THREE.Mesh
    SEAT_B001: THREE.Mesh
    Console006: THREE.Mesh
    SEAT_R001: THREE.Mesh
  }
  materials: {
    window: THREE.MeshStandardMaterial
    ['Abandoned Body']: THREE.MeshStandardMaterial
    ['Tyre Rubber']: THREE.MeshStandardMaterial
    silicon: THREE.MeshStandardMaterial
    ['dirty chrome']: THREE.MeshStandardMaterial
    underside: THREE.MeshStandardMaterial
    ['rim rusted']: THREE.MeshStandardMaterial
    ['Center Console']: THREE.MeshStandardMaterial
    base: THREE.MeshStandardMaterial
    ['black plastic']: THREE.MeshStandardMaterial
    ['seat and door']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/firstauto/vichle-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.glass.geometry} material={materials.window} />
      <mesh geometry={nodes.Body.geometry} material={materials['Abandoned Body']} position={[0.002, 0.754, -0.283]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.tire_rubber.geometry} material={materials['Tyre Rubber']} position={[0.024, -3.047, -2.923]} />
      <mesh geometry={nodes.silicon.geometry} material={materials.silicon} />
      <mesh geometry={nodes.Frame.geometry} material={materials['dirty chrome']} />
      <mesh geometry={nodes.Secondary_Details004.geometry} material={materials.underside} />
      <mesh geometry={nodes.FLR004.geometry} material={materials['rim rusted']} position={[-1.901, 0.012, 0]} scale={0.343} />
      <mesh geometry={nodes.Console004.geometry} material={materials['Center Console']} />
      <mesh geometry={nodes.SEAT_B001.geometry} material={materials.base} />
      <mesh geometry={nodes.Console006.geometry} material={materials['black plastic']} />
      <mesh geometry={nodes.SEAT_R001.geometry} material={materials['seat and door']} />
    </group>
  )
}

useGLTF.preload('/firstauto/vichle-transformed.glb')
